import fs from 'node:fs/promises';
import {Presentation, PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from 'C:/Users/roysaw77/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='C:/Users/roysaw77/Desktop/codenection-travel';
const skill='C:/Users/roysaw77/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const font=resolvePresentationFont();
const p=Presentation.create({slideSize:{width:1280,height:720}});
const ink='#173F3A', green='#176658', muted='#566C66';
function txt(s,t,x,y,w,h,size=28,color=ink,bold=false){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return a;}
function slide(title,n,notes,dark=false){const s=p.slides.add();s.background.fill=dark?'#173F3A':'#F7F8F3';if(title)txt(s,title,64,45,1152,90,44,dark?'#FFFFFF':ink,true);txt(s,String(n).padStart(2,'0'),1160,667,55,28,17,dark?'#BDCCC6':muted);s.speakerNotes.textFrame.setText(notes);return s;}
async function shot(s,name,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(`${root}/docs/screenshots/${name}.png`)),contentType:'image/png',alt:name,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
async function logo(s,name,x,y,w,h,contentType='image/png'){s.images.add({blob:new Uint8Array(await fs.readFile(`${root}/.ppt-build/logos/${name}`)),contentType,alt:`${name.replace(/\..+$/,'')} logo`,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
function item(s,label,body,x,y,w=510){txt(s,label,x,y,w,42,29,green,true);txt(s,body,x,y+49,w,90,25);}
let s=slide('',1,'Timing: 20 seconds.\nSenior Travel Companion helps adult children support older parents when they cannot travel together. We focus on parents aged sixty and above who join organised tours. The child helps choose the trip, the parent uses a simple interface, and the guide provides local support. This is our proposed product, illustrated through a UI prototype.',true);
txt(s,'Senior Travel\nCompanion',72,175,1080,190,76,'#FFFFFF',true);txt(s,'Helping families support older parents\nbefore and during a tour',78,420,950,110,34,'#D4E4DD');txt(s,'Hackathon concept and UI prototype',78,610,950,40,22,'#BBD0C6');
s=slide('The family support gap',2,'Timing: 30 seconds.\nImagine a daughter arranging a holiday for her mother, who prefers short walks. A tour listing may look suitable, but she still needs to understand walking demands and the evidence behind the operator. During the trip, a missed reply gives little context. The parent also needs a simple way to ask for help. These are hypotheses we will validate through family and guide interviews.');
txt(s,'“Can Mum manage the trip,\nand who can help if plans change?”',70,161,1100,125,40,ink,true);item(s,'Before the trip','Suitability and important tour details\ncan be difficult to assess.',72,350);item(s,'During the trip','Children need context. Parents need\nan easy way to request support.',686,350);txt(s,'Primary user / intended payer: adult child     End user: parent aged 60+',72,594,1120,42,22,muted);
s=slide('Tour matching with reasons',3,'Timing: 40 seconds.\nThe child enters a parent profile with walking tolerance, rest needs, language and budget. The proposed matcher compares it with tour, guide, itinerary and safety information. Explicit rules calculate suitability, while the AI advisor explains the fit and missing information. For example, a forty-minute walk should be flagged for a parent who prefers twenty minutes. The Trust Profile shows supporting evidence and review status. Our displayed scores are fixed demo values, and neither suitability nor a trust profile guarantees safety.');
item(s,'AI Senior Tour Matcher','Parent preferences compared\nwith tour requirements.',70,170,550);item(s,'AI Travel Advisor','Suitability Score with reasons,\nmismatches and unknowns.',70,320,550);item(s,'Tour Trust Profile','Guide, licence, insurance, hotel\nand transport evidence.',70,470,550);await shot(s,'v2-03-advisor',690,148,245,495);await shot(s,'v2-04-trust',948,148,245,495);
s=slide('Simple actions for older travellers',4,'Timing: 35 seconds.\nParents should not need to learn a complex dashboard. Senior Simple Mode brings the next stop and meeting details to the main screen. The largest action lets them say I am okay. Calling the guide and requesting help remain easy to find. We use short labels and prominent controls, with detailed planning in the child view. We still need usability testing with older adults, including text scaling and whether users understand the help actions.\nSources: https://www.w3.org/WAI/older-users/ and https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html');
await shot(s,'v2-07-parent',100,150,270,505);item(s,'One clear next step','Next stop and meeting information\non the home screen.',475,182,690);item(s,'Easy check-in','A prominent “I’m OK” action.',475,342,690);item(s,'Help within reach','Call guide or open SOS / Help.',475,492,690);
s=slide('Shared context when help is needed',5,'Timing: 35 seconds.\nThe child dashboard combines the itinerary with the latest check-in and a future trip map. The map concept shows the parent’s consented shared location, the next stop and the update time. It uses an illustrative map in this prototype and has no live tracking. If a parent requests rest or sends SOS, the proposed alert workflow contacts the authorised guide and child. The guide can respond locally while the child supports remotely. The app must show stale data and separate acknowledgements. These screenshots simulate the workflow. They do not send notifications or provide emergency response.');
item(s,'Child Dashboard','Itinerary, map preview and latest status\nin the same trip view.',70,190,570);item(s,'Smart Safety Alerts','SOS, overdue check-ins and\npossible route deviations.',70,350,570);txt(s,'Guide assists locally.\nChild follows the response remotely.',70,520,570,90,28,ink,true);await shot(s,'v2-05-dashboard',695,148,243,495);await shot(s,'v2-06-alerts',952,148,243,495);
s=slide('Our proposed difference',6,'Timing: 30 seconds.\nExisting products already solve useful parts of this problem. TourRadar offers senior tours and physical ratings. TripIt organises and shares itineraries. Life360 supports location sharing and SOS. Our proposed difference is joining parent-specific tour selection with support during travel, connecting the parent, child and guide. We are not claiming these individual features are unique. We need to validate whether this connected workflow matters enough for families to adopt and pay for.\nSources: https://www.tourradar.com/pa/seniors ; https://help.tourradar.com/en/operators/group-type-guide-type-physical-ratings ; https://help.tripit.com/en/support/solutions/articles/103000063304-getting-started ; https://www.life360.com/location-sharing ; https://support.life360.com/hc/en-us/articles/23053474049687-SOS-Alerts\nLogo sources: https://www.tourradar.com/press ; https://www.tripit.com/themes/custom/tripit_theme/images/logo-tripit.svg ; https://commons.wikimedia.org/wiki/File:Life360_Horizontal.svg');
item(s,'TourRadar','Tour discovery and physical ratings',75,160,790);await logo(s,'tourradar.png',960,153,220,60);item(s,'TripIt','Travel plans and itinerary sharing',75,282,790);await logo(s,'tripit-clean.png',955,268,225,76);item(s,'Life360','Family location sharing and SOS',75,404,790);await logo(s,'life360.png',955,401,225,60);txt(s,'Our focus: parent-specific tour selection\nconnected to family and guide support',75,558,1100,92,34,ink,true);
s=slide('A focused implementation stack',7,'Timing: 30 seconds.\nOur planned frontend is Flutter, backed by FastAPI and Supabase for profiles, trips and permissions. LangChain sends relevant evidence to NVIDIA NIM to explain matches. Backend rules control scoring and alerts. For routing, Geoapify is a lower-cost MVP candidate, subject to local coverage tests. FCM and a persistent worker handle notifications and overdue events. The existing demo uses HTML, CSS and JavaScript. These integrations are planned, and we will confirm provider limits before implementation.\nSources: https://docs.flutter.dev/platform-integration/web ; https://supabase.com/docs/guides/database/overview ; https://docs.langchain.com/oss/python/langchain/structured-output ; https://docs.api.nvidia.com/nim/re/reference/llm-apis ; https://www.geoapify.com/pricing/ ; https://firebase.google.com/docs/cloud-messaging');
item(s,'Flutter','Parent, child and guide interfaces',70,165);item(s,'FastAPI + Supabase','APIs, trip data and access controls',690,165);item(s,'LangChain + NVIDIA NIM','Evidence-based match explanations',70,335);item(s,'Geoapify Routing API','Proposed route distance and duration',690,335);txt(s,'FCM + persistent worker for notifications and scheduled checks',70,535,1130,70,28,green,true);txt(s,'Planned stack. Current prototype uses HTML, CSS and JavaScript.',70,617,1120,40,22,muted);
s=slide('The next milestone',8,'Timing: 20 seconds.\nOur next milestone is one working trip across two devices: a child creates a profile, reviews a match and receives a parent check-in. Then we test guide acknowledgement and usability with older adults. Today we have the interface concept. Our goal is to help families choose a suitable tour and stay connected when they cannot travel together.',true);
txt(s,'One profile. One suitable tour.\nOne shared trip.',75,177,1110,145,53,'#FFFFFF',true);txt(s,'Next: working check-ins across two devices\nThen: guide response and older-user testing',78,391,1110,100,31,'#D4E4DD');txt(s,'Current status: UI prototype with sample data',78,577,1100,50,25,'#BDCCC6');
await (await PresentationFile.exportPptx(p)).save(root+'/.ppt-build/candidate.pptx');
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(root+`/.ppt-build/slide-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
const result=await finalizePresentation({workspaceDir:root,candidatePath:root+'/.ppt-build/candidate.pptx',finalPath:root+'/output/Senior_Travel_Companion_4_Minute_Pitch_v2.pptx',pythonExecutable:'C:/Users/roysaw77/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:root+'/.ppt-build/validation-v2.json'});console.log(JSON.stringify(result));
