'use strict';
const screen = document.getElementById('screen');
const nav = document.getElementById('app-nav');
const initial = () => ({ role:'parent', page:'home', checkin:false, request:'', sharing:'status', pending:false, accepted:false, stale:false, offline:false, size:0, saved:false, declined:false, destination:'Penang', budget:'250', pace:'Short walks with regular rests', prepared:false });
let state = initial();
const paths = { check:'m5 12 4 4L19 6', arrow:'m9 5 7 7-7 7', back:'m15 5-7 7 7 7', clock:'M12 8v4l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0', pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0 M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0', home:'m3 10 9-7 9 7 M5 9v12h5v-7h4v7h5V9', calendar:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16', family:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M2 21v-3a6 6 0 0 1 12 0v3 M17 4a4 4 0 0 1 0 8 M17 15a5 5 0 0 1 5 5v1', phone:'M6 3H3c-1 10 8 19 18 18v-4l-5-2-2 3c-4-2-6-4-8-8l3-2-3-5Z', help:'M12 8v5 M12 17h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0', walk:'M14 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3 M7 10l4-4 4 4 4 1 M11 6l-1 8-4 7 M10 14l6 3v5', shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6z m-5 10 3 3 7-7', rest:'M4 8h13v7a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5z M17 9h2a3 3 0 0 1 0 6h-2 M7 2v3 M12 2v3' };
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.check}"/></svg>`;}
function button(label, action, style='primary', ico=''){return `<button class="action ${style}" data-action="${action}">${ico?icon(ico):''}${label}</button>`;}
function back(to='home'){return `<button class="back" data-action="${to}">${icon('back')}Back</button>`;}
function note(title,text='',style=''){return `<div class="status-note ${style}"><strong>${title}</strong>${text}</div>`;}
function title(name,sub=''){return `<h2>${name}</h2>${sub?`<p class="sub">${sub}</p>`:''}`;}
function escapeText(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function activity(){return state.accepted?'Rest at Garden Cafe':'Penang State Museum';}
function home(){return `<div class="greeting"><div><p>Saturday, 12 September</p><h2>Good morning, Mei.</h2></div><button class="text-size" data-action="text">${state.size===0?'Larger text':state.size===1?'Text 200%':'Standard text'}</button></div>
${state.offline?note('You are offline','Your saved plan is still here. Check-ins cannot be sent.','warn'):state.checkin?note('Check-in shared with Anna',`You said: "${state.checkin}". Updated just now.`):''}
${state.pending?button('Anna suggested a change','change','','calendar'):''}
${state.accepted?`<span class="tag">${icon('check')}Your change is confirmed</span>`:''}
<article class="next"><div class="next-body"><p class="next-label">YOUR NEXT STOP</p><div class="time">10:30 AM</div><h3>${activity()}</h3><div class="detail">${icon('walk')}About ${state.accepted?'8':'22'} minutes on foot</div><div class="detail">${icon('clock')}Leave at ${state.accepted?'10:20':'10:05'} AM</div></div><div class="next-footer">${icon('calendar')}Lunch stays at 1:00 PM</div></article>
${button(state.checkin?'Send another check-in':'I am okay','checkin','primary','check')}
${button('I need help','help','danger','help')}
${button('Where do I go?','directions','','pin')}
<p class="footnote">${state.sharing==='none'?'Sharing is off.':`Sharing ${state.sharing==='status'?'status only':state.sharing+' location'} with Anna.`} You are in control.</p>`;}
function help(){return back()+title('How can we help?','Choose what you need. No typing needed.')+`<div class="stack"><button class="option" data-action="rest">${icon('rest')}<span class="copy">I need a rest<small>Ask Anna to help adjust the plan.</small></span>${icon('arrow')}</button><button class="option" data-action="late">${icon('clock')}<span class="copy">I am running late<small>Let Anna know about the delay.</small></span>${icon('arrow')}</button><button class="option" data-action="call">${icon('phone')}<span class="copy">Call my daughter<small>Anna Lee</small></span>${icon('arrow')}</button><button class="option danger" data-action="urgent">${icon('help')}<span class="copy">I need help now<small>Ask Anna to contact me.</small></span>${icon('arrow')}</button></div><p class="footnote">This app does not contact emergency services.</p>`;}
function sent(){return back()+`<div class="success-icon">${icon('check')}</div>`+title('Your request is shared.',`Anna can see: "${state.request}".`)+note('You can call Anna too','A shared request does not mean Anna has seen it yet.')+button('Call my daughter','call','primary','phone')+button('Back to today','home','')+`<p class="footnote">Prototype: the update appears in Family view only.</p>`;}
function call(){return back('help')+title('Call Anna', 'Your daughter and trusted contact.')+`<div class="contact"><span class="avatar">AL</span><div><strong>Anna Lee</strong><p>Helping from home</p></div></div>`+note('Call preview','In the finished app, this action would open your phone dialler. No call is placed in this prototype.')+button('Back to today','home') ;}
function plan(){return title('Your day','Saturday, 12 September · Penang')+`<ol class="schedule"><li class="done"><time>8:30 AM</time><section><h3>Breakfast at the hotel</h3><p>Finished</p></section></li><li class="current"><time>10:30 AM</time><section><h3>${activity()}</h3><p>About ${state.accepted?'8':'22'} minutes walking</p><span class="tag">Next activity</span></section></li><li><time>1:00 PM</time><section><h3>Lunch with the group</h3><p>Meet at the restaurant entrance.</p><span class="tag">Fixed meeting time</span></section></li><li><time>3:00 PM</time><section><h3>Back to the hotel</h3><p>Time to rest.</p></section></li></ol>`+button('Back to today','home','');}
function directions(){return back()+title('Your next stop',activity())+`<div class="next"><div class="next-body"><div class="detail">${icon('clock')}Leave at ${state.accepted?'10:20':'10:05'} AM</div><div class="detail">${icon('walk')}Allow about ${state.accepted?'8':'22'} minutes</div><div class="detail">${icon('pin')}Meet at the main entrance</div></div></div>`+note('Confirm the route before leaving','This sample itinerary has no live navigation. Ask Anna or your tour organiser if you are unsure.','warn')+button('Call my daughter','call','primary','phone')+button('I have arrived','arrived','','check');}
function sharing(){return title('Your family','Choose what Anna can see.')+`<div class="contact"><span class="avatar">AL</span><div><strong>Anna Lee</strong><p>Your daughter · Trusted contact</p></div></div><form id="sharing-form"><fieldset><legend>Share with Anna</legend>${[['none','Nothing for now','Stop status and location sharing.'],['status','My updates only','Check-ins and requests. No location.'],['approximate','My updates and area','A general area, not an exact location.'],['precise','My updates and exact location','Only for this trip, until 13 September.']].map(([v,l,d])=>`<label class="choice"><input type="radio" name="sharing" value="${v}" ${state.sharing===v?'checked':''}><span>${l}<small>${d}</small></span></label>`).join('')}</fieldset><p class="sub">You can change your mind at any time.</p><button class="action primary" type="submit">Save my choice</button></form>${state.saved?note('Your choice is saved','Anna can only see what you allow.'):''}<p class="footnote">This prototype simulates permissions. It never requests your device location.</p>`;}
function childHome(){let status = state.sharing==='none'?'Sharing is off':state.request?state.request:state.stale?'Location update is old':state.checkin?'Mum checked in':'No check-in yet';return `<div class="greeting"><div><p>Saturday, 12 September</p><h2>Mum's trip, at a glance.</h2></div><span class="avatar secondary">AL</span></div><span class="tag">${icon('pin')}${escapeText(state.destination)} · Day 2 of 3</span><article class="metric"><div class="metric-head"><span class="avatar">ML</span><div><h3>Mei Lee</h3><span class="sub">Travelling independently today</span></div></div>${note(status,state.sharing==='none'?'Mei has paused sharing. Her current status and location are unavailable.':state.request?'Shared just now. Contact Mum to understand what she needs.':state.stale?'Last location update: 9:15 AM. Cause unknown. This does not mean Mum is in danger.':state.checkin?`"${state.checkin}" · Updated just now.`:'Next check-in: 10:30 AM.',state.request||state.stale?'warn':'')}<div class="meta"><span>Location access</span><strong>${state.sharing==='none'?'Off':state.sharing==='status'?'Not shared':state.sharing==='approximate'?'Approximate':'Precise'}</strong></div>${['precise','approximate'].includes(state.sharing)?`<p class="sub">${state.sharing==='precise'?'Sample: museum entrance':'Sample: central George Town'} · ${state.stale?'9:15 AM, outdated':'9:55 AM'}<br>Demo location, not live GPS.</p>`:''}</article>
${state.prepared?note('Preferences confirmed',`Budget: RM${escapeText(state.budget)} per person. ${escapeText(state.pace)}.`):''}
${state.pending?note('Waiting for Mum','Your suggested change has not been accepted yet.'):state.accepted?note('Mum accepted your suggestion','Garden Cafe is now in her itinerary.'):state.declined?note('Mum kept her original plan','Your suggestion was declined. You can discuss another option.'):''}
<h3>Next in the itinerary</h3><div class="detail">${icon('clock')}10:30 AM · ${activity()}</div><p class="sub">Lunch meeting stays at 1:00 PM.</p>${state.accepted?'':button('Suggest a shorter walk','replan','primary','rest')}${button('Contact Mum','contact','','phone')}
<details class="demo-controls"><summary>Prototype scenario controls</summary><button data-action="stale">Simulate an old location update</button><button data-action="offline">Simulate parent offline</button></details>`;}
function comparison(){return `<div class="compare"><div><p>CURRENT PLAN</p><h3>Museum</h3><strong>22 min</strong><p>estimated walking</p><p>RM15 estimated</p></div><div><p>SUGGESTED PLAN</p><h3>Garden Cafe</h3><strong>8 min</strong><p>estimated walking</p><p>RM12 estimated</p></div></div><span class="tag">${icon('check')}Lunch stays at 1:00 PM</span>`;}
function replan(){return back()+title('A little more rest','Suggest one change. Keep the rest of the day.')+`<div class="request"><p>${state.request?`Mum said: "${state.request}"`:'A shorter walk could leave more time to rest.'}</p></div>`+comparison()+note('Check before suggesting','Cafe access and arrival time need confirmation. These are sample estimates.','warn')+button('Send suggestion to Mum','suggest')+button('Keep current plan','home','')+`<p class="footnote">For an organised tour, coordinate changes with the organiser first. This demo uses an independent outing.</p>`;}
function change(){return back()+title('A suggestion from Anna','Would you like a shorter walk?')+comparison()+`<p class="sub" style="margin-top:20px">Rest at a nearby cafe instead of visiting the museum. The rest of your day stays the same.</p>`+note('Please check together','Cafe access and travel times still need confirmation.','warn')+button('Accept this change','accept','primary','check')+button('Keep my original plan','decline','');}
function setup(){return title('Prepare together','Let Mum confirm what works for her.')+`<form id="trip-form"><label class="field">Destination<input name="destination" value="${escapeText(state.destination)}" readonly></label><label class="field">Budget per person (RM)<input name="budget" type="number" min="1" max="100000" value="${escapeText(state.budget)}" required></label><label class="field">Walking preference<select name="pace"><option ${state.pace==='Short walks with regular rests'?'selected':''}>Short walks with regular rests</option><option ${state.pace==='Flexible pace'?'selected':''}>Flexible pace</option></select></label><button class="action primary" type="submit">Review preferences with Mum</button></form><p class="footnote">This sample trip stays in Penang. Preferences are entered manually. AI extraction and account invitations are not connected.</p>`;}
function review(){return back('setup')+title('Does this look right?','Review these details together before saving.')+`<article class="metric"><h3>${escapeText(state.destination)}</h3><p>Budget: RM${escapeText(state.budget)} per person</p><p>${escapeText(state.pace)}</p><p>Keep the 1:00 PM lunch meeting.</p></article>`+button('We confirm these preferences','confirm')+button('Edit details','setup','');}
function contact(){return back()+title('Contact Mum','Choose a person to speak to.')+`<div class="contact"><span class="avatar">ML</span><div><strong>Mei Lee</strong><p>Mother · Travelling in Penang</p></div></div>`+button('Preview call to Mum','previewcall','primary','phone')+note('No local contact added','Agree on an actual local contact before the trip. Anna is helping remotely.')+`<p class="footnote">No real phone number is stored in this demo.</p>`;}
function render(focus=false){document.querySelector('.app-shell').classList.toggle('family',state.role==='child');screen.className=state.role==='parent'?(state.size===1?'large':state.size===2?'double':''):'';document.querySelectorAll('[data-role]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.role===state.role));const pages={home:state.role==='parent'?home:childHome,help,sent,call,plan,directions,sharing,replan,change,setup,review,contact,previewcall:()=>back('contact')+title('Call preview')+note('No call placed','The finished app would open your phone dialler to call Mum.')+button('Back to trip','home')};screen.innerHTML=(pages[state.page]||pages.home)();let items=state.role==='parent'?[['home','Today','home'],['plan','My day','calendar'],['sharing','Family','family']]:[['home','Overview','home'],['setup','Prepare','calendar'],['contact','Contacts','family']];nav.className='nav';nav.innerHTML=items.map(([p,l,i])=>`<button data-action="${p}" ${state.page===p?'aria-current="page"':''}>${icon(i)}${l}</button>`).join('');if(focus){screen.focus({preventScroll:true});document.querySelector('.app-shell').scrollIntoView({block:'start',behavior:'instant'});}}
function announce(text){document.getElementById('announcement').textContent=text;}
function go(page){state.page=page;state.saved=false;render(true);}
document.addEventListener('click',event=>{const role=event.target.closest('[data-role]');if(role){state.role=role.dataset.role;go('home');return;}const b=event.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;
if(action==='text'){state.size=(state.size+1)%3;render();document.querySelector('[data-action="text"]').focus();return;}
if(action==='checkin'||action==='arrived'){if(state.offline){announce('You are offline. Your check-in was not sent.');go('home');return;}if(state.sharing==='none'){go('sharing');announce('Choose what to share before sending a check-in.');return;}state.checkin=action==='arrived'?'I have arrived':'I am okay';state.request='';go('home');announce('Check-in shared with Anna in this demo.');return;}
if(['rest','late','urgent'].includes(action)){if(state.offline){go('home');announce('You are offline. The request could not be sent.');return;}if(state.sharing==='none'){go('sharing');announce('Choose sharing permissions before sending a request.');return;}state.request={rest:'I need a rest',late:'I am running late',urgent:'I need help now'}[action];go('sent');return;}
if(action==='suggest'){state.pending=true;state.declined=false;go('home');announce('Suggestion ready in Parent view.');return;}
if(action==='accept'){state.accepted=true;state.pending=false;state.request='';go('home');announce('Change accepted. Your itinerary is updated.');return;}
if(action==='decline'){state.pending=false;state.declined=true;go('home');announce('Original plan kept.');return;}
if(action==='stale'){state.sharing='approximate';state.stale=true;state.request='';go('home');return;}
if(action==='offline'){state.offline=true;state.role='parent';go('home');return;}
if(action==='confirm'){state.prepared=true;go('home');announce('Preferences confirmed for this demo.');return;}
go(action);
});
document.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);if(event.target.id==='sharing-form'){state.sharing=data.get('sharing');state.saved=true;render();announce('Sharing preference saved.');}if(event.target.id==='trip-form'){state.destination=data.get('destination');state.budget=data.get('budget');state.pace=data.get('pace');go('review');}});
document.getElementById('reset').addEventListener('click',()=>{state=initial();render(true);announce('Demo reset.');});
render();
