const tours = [
  {name:'Penang at an Easy Pace',place:'George Town, Penang',days:'3 days',price:'890',score:92,tags:['Short walks','Mandarin guide'],tone:'green',walk:'15 min',group:'12 guests',hotel:'Heritage Garden Hotel',guide:'Daniel Tan',initials:'DT',transport:'Air-conditioned minibus',desc:'Heritage streets, local flavours and time to rest.',bars:[['Walking & rest',96],['Language',100],['Budget',89],['Stay & transport',83]],caution:'Hotel step-free entrance needs confirmation.'},
  {name:'Cameron Highlands Retreat',place:'Tanah Rata, Pahang',days:'3 days',price:'1050',score:84,tags:['Cool weather','Small group'],tone:'blue',walk:'25 min',group:'10 guests',hotel:'Highland Lodge',guide:'Sarah Lim',initials:'SL',transport:'Air-conditioned coach',desc:'Tea gardens, fresh air and a gentler morning routine.',bars:[['Walking & rest',78],['Language',100],['Budget',75],['Stay & transport',83]],caution:'Some garden paths include slopes and steps.'},
  {name:'Malacca Heritage Weekend',place:'Bandar Hilir, Malacca',days:'2 days',price:'620',score:76,tags:['Within budget','Heritage sights'],tone:'gold',walk:'35 min',group:'18 guests',hotel:'Riverside Stay',guide:'Amir Lee',initials:'AM',transport:'Tour coach',desc:'Riverside sights and stories from the old town.',bars:[['Walking & rest',58],['Language',100],['Budget',95],['Stay & transport',51]],caution:'Long outdoor walks may exceed Mei’s preference.'}
];
const currentTour = () => tours[state.tour];
const badge = (text,kind='') => `<span class="badge ${kind}">${text}</span>`;
const row = (label,value) => `<div class="data-row"><span>${label}</span><strong>${value}</strong></div>`;
const smallLink = (text,page) => `<button class="text-link" data-action="${page}">${text}${icon('arrow')}</button>`;
const pageHead = (label,heading,action='')=>`<div class="page-head"><div><p class="eyebrow">${label}</p><h2>${heading}</h2></div>${action}</div>`;
const contactTile = (initials,name,role) => `<div class="person-row"><span class="avatar">${initials}</span><div><strong>${name}</strong><small>${role}</small></div></div>`;
const mapPreview = (expanded=false) => `<${expanded?'div':'button'} class="map-card ${expanded?'map-expanded':''}" ${expanded?'':'data-action="map"'}>
  <div class="map-frame">
    <img src="assets/george-town-route-map.png" alt="Illustrative street map of George Town with Mei’s planned walking route">
    <span class="map-person" aria-label="Mei and her tour group"><span>ML</span></span>
    <span class="map-stop" aria-hidden="true">${icon('pin')}</span>
    <span class="map-place map-place-mei"><strong>Mum &amp; group</strong><small>10:15 AM · sample</small></span>
    <span class="map-place map-place-stop"><strong>${state.accepted?'Garden Cafe':'State Museum'}</strong><small>${state.accepted?'8':'15'} min walk</small></span>
    <span class="map-future">Future feature</span>
  </div>
  ${expanded?'':`<span class="map-card-footer"><span><strong>Trip map preview</strong><small>See Mum’s shared location and next stop</small></span>${icon('arrow')}</span>`}
</${expanded?'div':'button'}>`;

function toursPage(){return pageHead('AI SENIOR TOUR MATCHER','A good fit for Mum',`<button class="avatar profile-btn" data-action="profile" aria-label="Open parent profile">ML</button>`)+
`<button class="profile-strip" data-action="profile"><span>${icon('family')}</span><div><strong>Mei, 68</strong><small>Easy pace · Mandarin · Under RM1,000</small></div>${icon('arrow')}</button>
<div class="destination-line">Malaysia <span>September</span></div>
<div class="chips" aria-label="Tour filters">${['All tours','Easy pace','Under RM1,000'].map(x=>`<button data-filter="${x}" aria-pressed="${state.filter===x}">${x}</button>`).join('')}</div>
<div class="section-line"><h3>Recommended tours</h3><span>Sample matches</span></div>
<div class="tour-list">${tours.map((t,i)=>({t,i})).filter(({i})=>state.filter==='All tours'||(state.filter==='Easy pace'?i===0:i!==1)).map(({t,i})=>`<article class="tour-card"><div class="tour-band ${t.tone}"><span>${t.days} · ${t.group}</span><strong>${t.score}<small>/100 match</small></strong></div><div class="tour-content"><p class="location">${t.place}</p><h3>${t.name}</h3><div class="tag-row">${t.tags.map(x=>badge(x)).join('')}</div><div class="tour-bottom"><div><strong>RM${t.price}</strong><small>per person</small></div><button class="primary compact" data-tour="${i}">View tour ${icon('arrow')}</button></div></div></article>`).join('')}</div>`;}

function profile(){return back('tours')+pageHead('PARENT PROFILE','Meet Mei')+contactTile('ML','Mei Lee','68 years old')+
`<form id="profile-form"><div class="form-grid"><label class="field">Walking comfort<select><option>Up to 20 minutes</option><option>Up to 10 minutes</option><option>Up to 30 minutes</option></select></label><label class="field">Rest breaks<select><option>Every hour</option><option>Every 30 minutes</option></select></label><label class="field">Preferred language<select><option>Mandarin</option><option>English</option><option>Malay</option></select></label><label class="field">Budget per person<select><option>Under RM1,000</option><option>Under RM1,500</option></select></label></div><h3 class="section-title">Travel preferences</h3><div class="preference-grid">${['Fewer stairs','Hotel lift','Halal meals','Small group'].map((x,i)=>`<label class="preference"><input type="checkbox" ${i!==2?'checked':''}>${x}</label>`).join('')}</div><button class="action primary" type="submit">See tour matches ${icon('arrow')}</button><p class="micro">Preview profile · Scores are sample values.</p></form>`;}

function tourDetail(){const t=currentTour();return back('tours')+`<div class="tour-hero ${t.tone}"><p>${t.place}</p><h2>${t.name}</h2><span>${t.days} · ${t.group}</span></div><div class="score-strip"><div><span class="score-mini">${t.score}</span><span>Suitability score<small>Illustrative match</small></span></div>${smallLink('Why this score','advisor')}</div><p class="sub">${t.desc}</p><div class="facts"><div>${icon('walk')}<strong>${t.walk}</strong><span>longest walk</span></div><div>${icon('rest')}<strong>Hourly</strong><span>rest breaks</span></div><div>${icon('family')}<strong>Mandarin</strong><span>guide language</span></div></div>${smallLink('Tour trust profile','trust')}<div class="section-line"><h3>Itinerary preview</h3>${smallLink('Full plan','tourplan')}</div><div class="itinerary-mini">${[['DAY 1','Arrival & welcome dinner'],['DAY 2',state.tour===0?'Heritage walk & museum':state.tour===1?'Tea gardens & market':'Old town & river cruise'],['DAY 3','Breakfast & return journey']].slice(0,state.tour===2?2:3).map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div><div class="price-line"><div><strong>RM${t.price}</strong><span> / person</span></div>${badge('Sample tour')}</div>${button('View family dashboard','dashboard','primary','arrow')}`;}

function advisor(){const t=currentTour();return back('tour')+pageHead('AI SENIOR TRAVEL ADVISOR','How well does it fit?')+`<div class="advisor-score"><div class="score-ring" style="--score:${t.score}%"><div><strong>${t.score}</strong><span>out of 100</span></div></div><div><h3>${t.score>90?'Strong match':t.score>80?'Good match':'Some trade-offs'}</h3><p>For Mei’s travel profile</p>${badge('Sample assessment')}</div></div><div class="input-tags">${['Parent profile','Tour','Guide','Itinerary','Safety info'].map(x=>`<span>${icon('check')}${x}</span>`).join('')}</div><h3 class="section-title">Match breakdown</h3>${t.bars.map(([label,n])=>`<div class="score-row"><div><span>${label}</span><strong>${n}/100</strong></div><div class="bar"><i style="width:${n}%"></i></div></div>`).join('')}<div class="insight"><h3>${icon('check')}Why it fits</h3><p>Mandarin-speaking guide and scheduled rest stops.</p></div><div class="insight warning"><h3>${icon('help')}Ask before choosing</h3><p>${t.caution}</p></div><p class="micro">Illustrative suitability, not a safety rating.</p>${button('Review tour details','tour')}`;}

function trust(){const t=currentTour();return back('tour')+pageHead('TOUR TRUST PROFILE','Know before you go')+`<p class="sub">${t.name}</p><div class="trust-summary">${icon('shield')}<div><strong>Transparent details</strong><small>Sample records · No credentials verified</small></div></div>${contactTile(t.initials,t.guide,'Mandarin & English · 8 years listed')}<div class="trust-list">${[
['Guide licence','Licence copy listed','Document review pending','shield'],
['Tour operator','Registration listed','Independent verification pending','family'],
['Travel insurance','Policy summary listed','Age limits & exclusions to confirm','shield'],
['Hotel',t.hotel,'Lift listed · Step-free access unconfirmed','home'],
['Transport',t.transport,'Seat belts listed · Boarding height unknown','pin'],
['Safety plan','Guide + family contacts','First-aid kit listed · Response arrangements to confirm','shield']
].map(([a,b,c,i])=>`<details class="trust-item"><summary>${icon(i)}<span><strong>${a}</strong><small>${b}</small></span><span class="expand">+</span></summary><div class="trust-detail"><p>${c}</p><span>Source: sample operator listing</span><span>Updated: 12 Sep 2026</span></div></details>`).join('')}</div><div class="insight warning"><h3>2 things to clarify</h3><p>Hotel access and insurance eligibility.</p></div>${button('View daily itinerary','tourplan','','calendar')}`;}

function tourPlan(){return back('tour')+pageHead('TOUR ITINERARY','A day at an easy pace')+`<div class="chips"><span class="selected-label">Day 2</span><span>Meals & transport included</span></div>`+timeline(state.tour)+`<div class="facts"><div>${icon('walk')}<strong>45 min</strong><span>total walking</span></div><div>${icon('rest')}<strong>3 stops</strong><span>scheduled rests</span></div><div>${icon('clock')}<strong>3:00 PM</strong><span>back at hotel</span></div></div>`;}

function dashboard(){return pageHead('CHILD DASHBOARD','Mum’s day',`<span class="avatar secondary">AL</span>`)+`<div class="trip-label">${icon('pin')}Penang · Day 2 of 3</div><article class="parent-status">${contactTile('ML','Mei Lee','With Daniel’s tour group')}<div class="status-line">${badge(state.sharing==='none'?'Sharing off':state.checked?'Checked in':'On schedule',state.sharing==='none'?'neutral':'')}<span>${state.sharing==='none'?'':state.checked?'Just now':'10:15 AM · sample'}</span></div></article>${mapPreview()}<div class="dashboard-grid"><div><span>Next stop</span><strong>${state.accepted?'Garden Cafe':'State Museum'}</strong><small>10:30 AM</small></div><div><span>Next meeting</span><strong>Main entrance</strong><small>1:00 PM · Lunch</small></div></div><button class="alert-preview" data-action="alerts">${icon('shield')}<span><strong>Safety centre</strong><small>Guide + family contacts</small></span>${icon('arrow')}</button><div class="section-line"><h3>Today’s itinerary</h3>${smallLink('View all','tourplan')}</div><div class="itinerary-mini"><div><span>10:30</span><strong>${state.accepted?'Rest at Garden Cafe':'Penang State Museum'}</strong></div><div><span>13:00</span><strong>Lunch with the group</strong></div></div><div class="section-line"><h3>Your local contact</h3></div>${contactTile('DT','Daniel Tan','Tour guide · Sample contact')}<div class="two-actions">${button('Contact guide','contacts','','phone')}${button('Contact Mum','contacts','','phone')}</div>${smallLink('Suggest a shorter walk','replan')}`;}

function tripMap(){return back('dashboard')+pageHead('TRIP MAP','Mum’s shared location',badge('Future feature'))+mapPreview(true)+`<div class="map-status-list"><div>${icon('family')}<span><strong>Mum &amp; tour group</strong><small>Last sample update · 10:15 AM</small></span>${badge('On schedule')}</div><div>${icon('pin')}<span><strong>Next · ${state.accepted?'Garden Cafe':'State Museum'}</strong><small>${state.accepted?'8':'15'} min walk · Arrive around 10:30 AM</small></span></div></div><div class="insight"><h3>${icon('shield')}Location sharing is controlled by Mei</h3><p>This concept would show location only during the tour and only to approved family contacts.</p></div><p class="micro">Illustrative map and location. Live tracking is not connected in this prototype.</p>`;}

function alerts(){return pageHead('SMART SAFETY ALERTS','Safety centre')+`<div class="chips alert-tabs" aria-label="Alert scenario">${[['route','Off route'],['missed','No response'],['sos','SOS']].map(([v,l])=>`<button data-alert="${v}" aria-pressed="${state.alert===v}">${l}</button>`).join('')}</div>`+alertDetail();}
function alertDetail(){const items={route:['Possible route deviation','350 m from planned route','10:18 AM','Confirm with the guide before taking action.'],missed:['Check-in overdue','No reply for 30 minutes','10:30 AM','Try calling Mum or ask the guide to check in.'],sos:['SOS from Mei','Help requested','10:22 AM','Contact the guide and Mum.']};const [a,b,c,d]=items[state.alert];return `<article class="alert-detail ${state.alert==='sos'?'sos-detail':''}"><span class="alert-symbol">${icon(state.alert==='sos'?'help':'pin')}</span><h3>${a}</h3><p>${b}</p><span>${c} · Simulated event</span></article><div class="section-line"><h3>Alert recipients</h3>${badge('Sample status','neutral')}</div><div class="recipient">${contactTile('DT','Daniel Tan','Tour guide')}<span class="receipt">Acknowledged</span></div><div class="recipient">${contactTile('AL','Anna Lee','Daughter')}<span class="receipt pending">Not yet seen</span></div><p class="sub brief">${d}</p><div class="two-actions">${button('Call guide','contacts','primary','phone')}${button('Call Mum','contacts','','phone')}</div><p class="micro">UI scenario only. No alert or emergency call is sent.</p>`;}

function parentHome(){return `<div class="greeting"><div><p>Sunday, 13 September</p><h2>Hello, Mei.</h2></div><button class="text-size" data-action="text">${state.large?'Standard text':'Larger text'}</button></div>${state.checked?note('Check-in saved','Anna + Daniel · Demo'):''}${state.accepted?badge('New plan accepted'):''}<article class="next"><div class="next-body"><p class="next-label">NEXT STOP</p><h3>${state.accepted?'Garden Cafe':'State Museum'}</h3><div class="time">10:30 AM</div><div class="detail">${icon('walk')}${state.accepted?'8':'15'} min walk</div></div><div class="next-footer">${icon('clock')}Meet Daniel at the entrance</div></article><div class="meeting-reminder">${icon('calendar')}<div><strong>Lunch meeting · 1:00 PM</strong><small>Restaurant entrance</small></div></div>${button('I’m OK','checkin','primary','check')}<div class="two-actions">${button('Call guide','contacts','','phone')}${button('SOS / Help','help','danger','help')}</div>`;}
function helpPage(){return back('today')+title('What do you need?')+`<div class="stack">${button('I need a rest','rest','','rest')}${button('I’m running late','late','','clock')}${button('Call my daughter','contacts','','phone')}${button('SOS · Get help','sos','danger','help')}</div>`;}
function sosPage(){return back('help')+`<div class="sos-heading">${icon('help')}<h2>SOS preview</h2><p>Guide + daughter</p></div><div class="recipient">${contactTile('DT','Daniel Tan','Tour guide')}${badge('Recipient')}</div><div class="recipient">${contactTile('AL','Anna Lee','Daughter')}${badge('Recipient')}</div>${note('Demo only','No alert has been sent.','warn')}${button('Call guide','contacts','primary','phone')}${button('Back to today','today','')}`;}
function requestPage(){return back('today')+`<div class="success-icon">${icon('check')}</div>`+title(state.page==='rest'?'Rest request':'Running late')+`<p class="sub">For Anna + Daniel</p>${badge('Preview only')}${button('Back to today','today')}`;}
function timeline(tourId=0){const stop=state.accepted&&tourId===0?'Garden Cafe':['State Museum','Tea gardens','Old town walk'][tourId];const walk=state.accepted&&tourId===0?'8 min':tours[tourId].walk;return `<ol class="schedule">${[['8:30 AM','Hotel breakfast','Included'],['10:30 AM',stop,walk+' walk · Rest stop'],['1:00 PM','Group lunch','Meet at the entrance'],['3:00 PM','Return to hotel','Minibus transfer']].map(([a,b,c],i)=>`<li class="${i===1?'current':''}"><time>${a}</time><section><h3>${b}</h3><p>${c}</p></section></li>`).join('')}</ol>`;}
function parentPlan(){return title('My day','Penang · Day 2')+timeline();}
function sharingPage(){return title('My contacts')+contactTile('AL','Anna Lee','Daughter')+contactTile('DT','Daniel Tan','Tour guide')+`<h3 class="section-title">Share with Anna + Daniel</h3><form id="sharing-form">${[['none','Sharing off'],['status','My check-ins only'],['precise','Check-ins + location']].map(([v,l])=>`<label class="choice"><input type="radio" name="sharing" value="${v}" ${state.sharing===v?'checked':''}><span>${l}</span></label>`).join('')}<button class="action primary" type="submit">Save choice</button></form>${state.saved?note('Choice saved'):''}`;}
function contacts(){return back(state.role==='parent'?'today':'dashboard')+title('Contact someone')+contactTile('DT','Daniel Tan','Tour guide')+button('Call Daniel','callpreview','','phone')+(state.role==='parent'?contactTile('AL','Anna Lee','Daughter')+button('Call Anna','callpreview','','phone'):contactTile('ML','Mei Lee','Mother')+button('Call Mum','callpreview','','phone'))+`<p class="micro">Sample contacts · Calls are not connected.</p>`;}
function replan(){return back(state.role==='parent'?'today':'dashboard')+title('A shorter walk')+`<div class="compare"><div><small>Current</small><h3>Museum</h3><strong>15 min</strong></div><div><small>Suggested</small><h3>Garden Cafe</h3><strong>8 min</strong></div></div>${badge('1:00 PM lunch unchanged')}<p class="sub brief">Confirm access with Daniel.</p>`+button(state.role==='parent'?'Accept this change':'Preview Mum’s choice',state.role==='parent'?'accept':'parentchange')+button('Keep original plan',state.role==='parent'?'today':'dashboard','');}

const pages = {tours:toursPage,profile,tour:tourDetail,advisor,trust,tourplan:tourPlan,dashboard,map:tripMap,alerts,today:parentHome,help:helpPage,sos:sosPage,rest:requestPage,late:requestPage,plan:parentPlan,sharing:sharingPage,contacts,replan,callpreview:()=>back('contacts')+title('Call preview')+note('Not connected','No call is placed.')+button('Back to contacts','contacts')};
function go(page){state.page=page;render(true);}
function render(focus=false){
  document.querySelector('.app-shell').classList.toggle('family',state.role==='child');
  screen.className=state.role==='parent'&&state.large?'large':'';
  document.querySelectorAll('[data-role]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.role===state.role));
  document.querySelectorAll('[data-preview]').forEach(b=>b.classList.toggle('active',b.dataset.preview===state.page||(b.dataset.preview==='parent'&&state.role==='parent')));
  screen.innerHTML=(pages[state.page]||pages.tours)();
  const items=state.role==='parent'?[['today','Today','home'],['plan','My day','calendar'],['sharing','Contacts','family']]:[['tours','Discover','pin'],['dashboard','My trip','calendar'],['alerts','Alerts','shield'],['profile','Profile','family']];
  nav.className='nav';nav.style.gridTemplateColumns=`repeat(${items.length},minmax(0,1fr))`;
  nav.innerHTML=items.map(([p,l,i])=>`<button data-action="${p}" ${state.page===p?'aria-current="page"':''}>${icon(i)}${l}</button>`).join('');
  if(focus){screen.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
}
document.addEventListener('click',e=>{
  const role=e.target.closest('[data-role]');if(role){state.role=role.dataset.role;go(state.role==='parent'?'today':'tours');return;}
  const preview=e.target.closest('[data-preview]');if(preview){state.role=preview.dataset.preview==='parent'?'parent':'child';go(preview.dataset.preview==='parent'?'today':preview.dataset.preview);return;}
  const tour=e.target.closest('[data-tour]');if(tour){state.tour=Number(tour.dataset.tour);go('tour');return;}
  const filter=e.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;render();return;}
  const alert=e.target.closest('[data-alert]');if(alert){state.alert=alert.dataset.alert;render();return;}
  const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
  if(a==='text'){state.large=!state.large;render();document.querySelector('[data-action="text"]').focus();return;}
  if(a==='checkin'){state.checked=true;render();document.getElementById('announcement').textContent='Demo check-in saved.';return;}
  if(a==='parentchange'){state.role='parent';go('replan');return;}
  if(a==='accept'){state.accepted=true;go('today');return;}
  go(a);
});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='profile-form'){go('tours');}if(e.target.id==='sharing-form'){state.sharing=new FormData(e.target).get('sharing');state.saved=true;render();document.getElementById('announcement').textContent='Sharing choice saved.';}});
document.getElementById('reset').addEventListener('click',()=>{state=initial();render(true);});
render();
